stages:
  - test
  - deploy

test_backend_optimizer:
  stage: test
  tags:
    - g04-server
  script:
    - python -m pip install -r apps/backend/requirements.txt
    - python -m unittest discover -s apps/algoritmo_simplex/tests -p "test_*.py"
    - python -m unittest discover -s apps/backend/tests -p "test_*.py"

deploy:
  stage: deploy
  tags:
    - g04-server
  only:
    - develop
  script:
    - rsync -a --exclude='.git' $CI_PROJECT_DIR/ /home/cc06-g4/g04/
    - chmod +x /home/cc06-g4/g04/apps/backend/start.sh
    - sudo systemctl restart g04
